### ISSUE TITLE
FFmpeg error: Decryption has failed.

### ISSUE THREAD

**Issue by chaseoes** [roju/tiktok-live-recorder#15] opened 2023-10-20 20:18 UTC
I'm getting these errors fairly frequently. Sometimes it records fine, other times it gives this error and seems to prevent the entire recording from saving.

```
Press 'q' to re-start recording, CTRL + C to stop
frame= 5619 fps= 25 q=-1.0 Lsize=   49295kB time=00:03:46.54 bitrate=1782.5kbits/s speed=1.01x
2023-10-20 00:48:21,163 - INFO - Started recording
Press 'q' to re-start recording, CTRL + C to stop
frame=  165 fps= 26 q=-1.0 Lsize=     896kB time=00:00:06.68 bitrate=1098.2kbits/s speed=1.04x
2023-10-20 00:48:26,545 - ERROR - FFmpeg error:
2023-10-20 00:48:26,545 - ERROR - [tls @ 00000205497cbc00] Decryption has failed.
[tls @ 00000205497cbc00] The specified session has been invalidated for some reason.
[NULL @ 0000020549e4e640] Invalid NAL unit size (3078 > 1017).
[NULL @ 0000020549e4e640] missing picture in access unit with size 1021
[tls @ 00000205497cbc00] The specified session has been invalidated for some reason.
```

```
Press 'q' to re-start recording, CTRL + C to stop
frame=  165 fps=0.0 q=-1.0 Lsize=    2223kB time=00:00:07.18 bitrate=2536.5kbits/s speed=49.1x
2023-10-19 21:02:36,161 - INFO - Stream lagging
2023-10-19 21:02:43,282 - INFO - Started recording
Press 'q' to re-start recording, CTRL + C to stop
frame= 1593 fps= 29 q=-1.0 Lsize=   20250kB time=00:01:03.67 bitrate=2605.2kbits/s speed=1.17x
2023-10-19 21:03:46,510 - INFO - Started recording
Press 'q' to re-start recording, CTRL + C to stop
frame=  376 fps= 29 q=-1.0 Lsize=    2092kB time=00:00:15.16 bitrate=1130.3kbits/s speed=1.18x
2023-10-19 21:03:58,051 - ERROR - FFmpeg error:
2023-10-19 21:03:58,051 - ERROR - [tls @ 000001a18e8cbc00] Decryption has failed.
[tls @ 000001a18e8cbc00] The specified session has been invalidated for some reason.
[NULL @ 000001a18eb9e640] Invalid NAL unit size (4693 > 1856).
[NULL @ 000001a18eb9e640] missing picture in access unit with size 1860
[tls @ 000001a18e8cbc00] The specified session has been invalidated for some reason.
2023-10-19 21:04:04,971 - INFO - Started recording
Press 'q' to re-start recording, CTRL + C to stop
frame=  518 fps= 27 q=-1.0 Lsize=    3060kB time=00:00:20.86 bitrate=1201.7kbits/s speed= 1.1x
2023-10-19 21:04:22,864 - ERROR - FFmpeg error:
2023-10-19 21:04:22,864 - ERROR - [tls @ 0000018b1114bc00] Decryption has failed.
[tls @ 0000018b1114bc00] The specified session has been invalidated for some reason.
    Last message repeated 1 times
2023-10-19 21:04:29,939 - INFO - Started recording
Press 'q' to re-start recording, CTRL + C to stop
frame=108549 fps= 25 q=-1.0 Lsize=  650047kB time=01:12:56.42 bitrate=1216.8kbits/s speed=   1x
```

**Comment by roju** [comment] 2023-11-11 17:10
Duplicate of #11

**Closed** 2023-11-11 17:10 UTC
